---
language: java

script:
    - ./gradlew check assemble

install:
  - /bin/true

jdk:
- openjdk6
- oraclejdk7
- oraclejdk8

matrix:
  include:
  - jdk: openjdk6
    script: ./gradlew check assemble
  - jdk: oraclejdk7
    script: ./gradlew check assemble
  - jdk: oraclejdk8
    script: ./gradlew check assemble

branches:
  only:
  - master

notifications:
  email:
- vl.fedorchuck@gmail.com