---
language: java

install:
- npm install https://services.gradle.org/distributions/gradle-2.14-bin.zip
- /bin/true

jdk:
- openjdk6
- oraclejdk7
- oraclejdk8

script: ./gradlew check assemble

branches:
  only:
  - master